-- Add all missing areas from catalog.js that are not yet in the database
-- and add missing service categories (CCTV Technician, Solar Technician)

-- Add CCTV Technician and Solar Technician to service_categories
insert into public.service_categories (id, name, slug) values
  ('CCTV Technician', 'CCTV Technician', 'cctv-technician-faisalabad'),
  ('Solar Technician', 'Solar Technician', 'solar-technician-faisalabad')
on conflict (id) do update set name = excluded.name, slug = excluded.slug;

-- Add all missing areas from the frontend catalog
insert into public.areas (id, name, slug) values
  ('204 Chak', '204 Chak', '204-chak'),
  ('208 Chak', '208 Chak', '208-chak'),
  ('209 Chak', '209 Chak', '209-chak'),
  ('212 Chak', '212 Chak', '212-chak'),
  ('225 RB', '225 RB', '225-rb'),
  ('Abdullah Gardens', 'Abdullah Gardens', 'abdullah-gardens'),
  ('Agriculture University Area', 'Agriculture University Area', 'agriculture-university-area'),
  ('Al Noor Garden', 'Al Noor Garden', 'al-noor-garden'),
  ('Al-Fatah Garden', 'Al-Fatah Garden', 'al-fatah-garden'),
  ('Al-Haram Garden', 'Al-Haram Garden', 'al-haram-garden'),
  ('Ali Housing Colony', 'Ali Housing Colony', 'ali-housing-colony'),
  ('Amin Town', 'Amin Town', 'amin-town'),
  ('Aminpur Road', 'Aminpur Road', 'aminpur-road'),
  ('Ashrafabad', 'Ashrafabad', 'ashrafabad'),
  ('Asif Colony', 'Asif Colony', 'asif-colony'),
  ('Batala Colony', 'Batala Colony', 'batala-colony'),
  ('Bhawana Bazar', 'Bhawana Bazar', 'bhawana-bazar'),
  ('Bilal Town', 'Bilal Town', 'bilal-town'),
  ('Canal Garden', 'Canal Garden', 'canal-garden'),
  ('Chak No. 204 RB', 'Chak No. 204 RB', 'chak-no-204-rb'),
  ('Chak No. 208 RB', 'Chak No. 208 RB', 'chak-no-208-rb'),
  ('Chak No. 213 RB', 'Chak No. 213 RB', 'chak-no-213-rb'),
  ('Chak No. 214 RB', 'Chak No. 214 RB', 'chak-no-214-rb'),
  ('Chak No. 225 RB', 'Chak No. 225 RB', 'chak-no-225-rb'),
  ('Chak No. 226 RB', 'Chak No. 226 RB', 'chak-no-226-rb'),
  ('Chak No. 232 RB', 'Chak No. 232 RB', 'chak-no-232-rb'),
  ('Chak No. 240 RB', 'Chak No. 240 RB', 'chak-no-240-rb'),
  ('Chenab Gardens', 'Chenab Gardens', 'chenab-gardens'),
  ('Citi Housing Faisalabad', 'Citi Housing Faisalabad', 'citi-housing-faisalabad'),
  ('Civil Lines', 'Civil Lines', 'civil-lines'),
  ('Clock Tower Area', 'Clock Tower Area', 'clock-tower-area'),
  ('Eden Orchard', 'Eden Orchard', 'eden-orchard'),
  ('Eden Valley', 'Eden Valley', 'eden-valley'),
  ('Factory Area', 'Factory Area', 'factory-area'),
  ('Faizabad', 'Faizabad', 'faizabad'),
  ('G.M. Abad', 'G.M. Abad', 'gm-abad'),
  ('Garden City', 'Garden City', 'garden-city'),
  ('Ghanta Ghar', 'Ghanta Ghar', 'ghanta-ghar'),
  ('Green Town', 'Green Town', 'green-town'),
  ('GTS Chowk Area', 'GTS Chowk Area', 'gts-chowk-area'),
  ('Gulfishan Colony', 'Gulfishan Colony', 'gulfishan-colony'),
  ('Gulistan Colony', 'Gulistan Colony', 'gulistan-colony'),
  ('Hajvery Town', 'Hajvery Town', 'hajvery-town'),
  ('Hassan Town', 'Hassan Town', 'hassan-town'),
  ('Hussainabad', 'Hussainabad', 'hussainabad'),
  ('Iqbal Town', 'Iqbal Town', 'iqbal-town'),
  ('Islam Nagar', 'Islam Nagar', 'islam-nagar'),
  ('Islamia Park', 'Islamia Park', 'islamia-park'),
  ('Jamil Town', 'Jamil Town', 'jamil-town'),
  ('Jaranwala Road', 'Jaranwala Road', 'jaranwala-road'),
  ('Jhang Bazar', 'Jhang Bazar', 'jhang-bazar'),
  ('Jhumra Road', 'Jhumra Road', 'jhumra-road'),
  ('Jinnah Garden', 'Jinnah Garden', 'jinnah-garden'),
  ('Karkhana Bazar', 'Karkhana Bazar', 'karkhana-bazar'),
  ('Kashmir Road', 'Kashmir Road', 'kashmir-road'),
  ('Khayaban Colony', 'Khayaban Colony', 'khayaban-colony'),
  ('Khayaban-e-Amin', 'Khayaban-e-Amin', 'khayaban-e-amin'),
  ('Khayaban-e-Green', 'Khayaban-e-Green', 'khayaban-e-green'),
  ('Khayyam Town', 'Khayyam Town', 'khayyam-town'),
  ('Khurrianwala Road', 'Khurrianwala Road', 'khurrianwala-road'),
  ('Kohinoor City', 'Kohinoor City', 'kohinoor-city'),
  ('Kutchery Bazar', 'Kutchery Bazar', 'kutchery-bazar'),
  ('Lasani Garden', 'Lasani Garden', 'lasani-garden'),
  ('Lasani Pulli', 'Lasani Pulli', 'lasani-pulli'),
  ('Makkuana', 'Makkuana', 'makkuana'),
  ('Mansoorabad', 'Mansoorabad', 'mansoorabad'),
  ('Mehmoodabad', 'Mehmoodabad', 'mehmoodabad'),
  ('Millat Road', 'Millat Road', 'millat-road'),
  ('Model City', 'Model City', 'model-city'),
  ('Model Town', 'Model Town', 'model-town'),
  ('Montgomery Bazar', 'Montgomery Bazar', 'montgomery-bazar'),
  ('Mujahid Colony', 'Mujahid Colony', 'mujahid-colony'),
  ('Muslim Town', 'Muslim Town', 'muslim-town'),
  ('Narwala Road', 'Narwala Road', 'narwala-road'),
  ('Nazimabad', 'Nazimabad', 'nazimabad'),
  ('Nemat Colony', 'Nemat Colony', 'nemat-colony'),
  ('New Model Town', 'New Model Town', 'new-model-town'),
  ('Nishat Colony', 'Nishat Colony', 'nishat-colony'),
  ('Nishatabad', 'Nishatabad', 'nishatabad'),
  ('Noorpur', 'Noorpur', 'noorpur'),
  ('Officer City', 'Officer City', 'officer-city'),
  ('Officer Colony', 'Officer Colony', 'officer-colony'),
  ('Part 1 G.M. Abad', 'Part 1 G.M. Abad', 'part-1-gm-abad'),
  ('Part 2 G.M. Abad', 'Part 2 G.M. Abad', 'part-2-gm-abad'),
  ('Part 3 G.M. Abad', 'Part 3 G.M. Abad', 'part-3-gm-abad'),
  ('Part 4 G.M. Abad', 'Part 4 G.M. Abad', 'part-4-gm-abad'),
  ('Part 5 G.M. Abad', 'Part 5 G.M. Abad', 'part-5-gm-abad'),
  ('Part 6 G.M. Abad', 'Part 6 G.M. Abad', 'part-6-gm-abad'),
  ('Part 7 G.M. Abad', 'Part 7 G.M. Abad', 'part-7-gm-abad'),
  ('Part 8 G.M. Abad', 'Part 8 G.M. Abad', 'part-8-gm-abad'),
  ('Part 9 G.M. Abad', 'Part 9 G.M. Abad', 'part-9-gm-abad'),
  ('Peoples Colony No. 1', 'Peoples Colony No. 1', 'peoples-colony-no-1'),
  ('Peoples Colony No. 2', 'Peoples Colony No. 2', 'peoples-colony-no-2'),
  ('Peoples Colony No. 3', 'Peoples Colony No. 3', 'peoples-colony-no-3'),
  ('Peoples Colony No. 4', 'Peoples Colony No. 4', 'peoples-colony-no-4'),
  ('Peoples University Area', 'Peoples University Area', 'peoples-university-area'),
  ('Prime City', 'Prime City', 'prime-city'),
  ('Punjab Medical College Area', 'Punjab Medical College Area', 'punjab-medical-college-area'),
  ('Rabbani Colony', 'Rabbani Colony', 'rabbani-colony'),
  ('Rachna Town', 'Rachna Town', 'rachna-town'),
  ('Rail Bazar', 'Rail Bazar', 'rail-bazar'),
  ('Rasheedabad', 'Rasheedabad', 'rasheedabad'),
  ('Raza Garden', 'Raza Garden', 'raza-garden'),
  ('Razaabad', 'Razaabad', 'razaabad'),
  ('Rehman Gardens', 'Rehman Gardens', 'rehman-gardens'),
  ('Royal City', 'Royal City', 'royal-city'),
  ('Saeed Colony', 'Saeed Colony', 'saeed-colony'),
  ('Sargodha Road', 'Sargodha Road', 'sargodha-road'),
  ('Sandal Bar', 'Sandal Bar', 'sandal-bar'),
  ('Sandal Town', 'Sandal Town', 'sandal-town'),
  ('Shadab Colony', 'Shadab Colony', 'shadab-colony'),
  ('Sheikhupura Road', 'Sheikhupura Road', 'sheikhupura-road'),
  ('Sitara Colony', 'Sitara Colony', 'sitara-colony'),
  ('Small Industrial Estate', 'Small Industrial Estate', 'small-industrial-estate'),
  ('Tariqabad', 'Tariqabad', 'tariqabad'),
  ('Tech Town', 'Tech Town', 'tech-town'),
  ('University Town', 'University Town', 'university-town'),
  ('Usman Town', 'Usman Town', 'usman-town'),
  ('Wapda City', 'Wapda City', 'wapda-city'),
  ('Yasir Town', 'Yasir Town', 'yasir-town')
on conflict (id) do update set name = excluded.name, slug = excluded.slug;